# Databricks Module Configuration
# Converted from BMAD v4 expansion pack
# Version: 2.0.0
# Date: 2025-10-08

module:
  id: databricks
  name: Databricks Lakehouse Development Pack
  version: 2.0.0
  description: >
    Comprehensive expansion pack for Databricks Lakehouse system development with
    18 specialized agents, workflows, templates, checklists, and knowledge bases
    aligned to BMAD Core standards.
  author: BMAD Team
  original_version: 1.0.0
  conversion_date: 2025-10-08

# Module paths (relative to project root)
paths:
  agents: '{project-root}/bmad/databricks/agents'
  workflows: '{project-root}/bmad/databricks/workflows'
  data: '{project-root}/bmad/databricks/data'
  checklists: '{project-root}/bmad/databricks/checklists'
  legacy_tasks: '{project-root}/bmad/databricks/legacy/tasks'
  legacy_templates: '{project-root}/bmad/databricks/legacy/templates'

# Core Configuration Values (inherited or override from BMB)
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
output_folder: '{config_source}:output_folder'
config_source: '{project-root}/bmad/bmb/config.yaml'

# Module-specific settings
databricks:
  default_cloud: aws
  default_region: us-east-1
  supported_clouds: [aws, azure, gcp]
  workspace_tiers: [standard, premium, enterprise]
  default_runtime: 14.3.x-scala2.12
  unity_catalog_enabled: true

# Agent configuration
agents:
  count: 18
  prefix: databricks
  slash_command_prefix: databricks
  default_locale: zh-CN
  supported_locales: [zh-CN, en]

# Components inventory
components:
  agents: 18
  data_files: 206
  checklists: 315
  legacy_tasks: 374  # Available for on-demand workflow conversion
  legacy_templates: 358  # Available for on-demand workflow conversion
  workflows: 0  # To be created on-demand from legacy tasks/templates

# Quality gates (module-level)
quality_gates:
  agents_require_menu_validation: true
  workflows_require_instructions: true
  all_paths_use_project_root: true
  chinese_content_preserved: true

# Compatibility
compatibility:
  bmad_core: '>=6.0.0'
  bmad_method: '>=1.10'
  original_pack_version: 1.0.0

# Installation status
installation:
  status: partial  # Agents converted, workflows pending on-demand conversion
  installed_date: 2025-10-08
  installed_by: convert-legacy workflow
  notes: >
    Phase 1 complete: Agents, data, checklists migrated.
    Phase 2 pending: Workflows require on-demand conversion from legacy tasks/templates.

# License and attribution
license: MIT
tags: [Databricks, Lakehouse, Unity-Catalog, Delta-Lake, MLOps, DataOps, FinOps]
links:
  original_repo: BMAD-METHOD-new/expansion-packs/bmad-databricks-expansion-pack
  documentation: '{project-root}/bmad/databricks/README.md'
  conversion_report: '{project-root}/docs/conversion-report-databricks-2025-10-08.md'
