name: "snowflake-query-failures"
description: "Query Failures/Degradation (Errors/Timeout/Cache)"
author: "BMAD Snowflake Team"
config_source: "{project-root}/bmad/snowflake/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"
date: system-generated
installed_path: "{project-root}/bmad/snowflake/workflows/snowflake-query-failures"
instructions: "{installed_path}/instructions.md"
default_output_file: "{output_folder}/incidents/snowflake-query-failures-{{date}}.md"
workflow_type: "action"
