name: "run-slo-workshop"
description: "SLO Workshop (Define SLIs/SLOs/Error Budgets)"
author: "BMAD Snowflake Team"
config_source: "{project-root}/bmad/snowflake/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"
date: system-generated
installed_path: "{project-root}/bmad/snowflake/workflows/run-slo-workshop"
instructions: "{installed_path}/instructions.md"
default_output_file: "{output_folder}/operations/run-slo-workshop-{{date}}.md"
workflow_type: "action"
