name: "snowflake-dynamic-table-lag"
description: "Dynamic Table Lag (Target Lag/Refresh/Errors)"
author: "BMAD Snowflake Team"
config_source: "{project-root}/bmad/snowflake/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"
date: system-generated
installed_path: "{project-root}/bmad/snowflake/workflows/snowflake-dynamic-table-lag"
instructions: "{installed_path}/instructions.md"
default_output_file: "{output_folder}/incidents/snowflake-dynamic-table-lag-{{date}}.md"
workflow_type: "action"
