# Validate Infrastructure - Workflow Configuration
# Converted from v4 task
name: "validate-infrastructure"
description: "Validate Snowflake infrastructure readiness for production (pre-prod gate)"
author: "BMAD Snowflake Team"

# Configuration
config_source: "{project-root}/bmad/snowflake/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"
date: system-generated

# Module path and components
installed_path: "{project-root}/bmad/snowflake/workflows/validate-infrastructure"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"

# Checklist reference
checklist: "{project-root}/bmad/snowflake/checklists/snowflake-infrastructure-checklist.md"

# Output configuration
default_output_file: "{output_folder}/gates/preprod-infra-validation-{{date}}.md"

# Workflow type
workflow_type: "document"
purpose: "quality-gate"
