version: 1
expectations:
  - name: not_null_id
    column: id
    rule: NOT NULL
    action: FAIL
  - name: valid_ts
    column: event_ts
    rule: event_ts >= now() - interval 1 day
    action: DROP
