name: "create-data-sharing-contract"
description: "Create Data Sharing Agreement"
author: "BMAD Snowflake Team"
config_source: "{project-root}/bmad/snowflake/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"
date: system-generated
installed_path: "{project-root}/bmad/snowflake/workflows/create-data-sharing-contract"
instructions: "{installed_path}/instructions.md"
default_output_file: "{output_folder}/data-sharing/create-data-sharing-contract-{{date}}.md"
workflow_type: "action"
