# Create Account Architecture - Workflow Configuration
# Converted from v4 task + template
name: "create-account-architecture"
description: "Generate Snowflake account/organization/identity and network architecture document"
author: "BMAD Snowflake Team"

# Configuration
config_source: "{project-root}/bmad/snowflake/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
output_folder: "{config_source}:output_folder"
date: system-generated

# Module path and components
installed_path: "{project-root}/bmad/snowflake/workflows/create-account-architecture"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"

# Output configuration
default_output_file: "{output_folder}/architecture/account-architecture-{{date}}.md"
workflow_type: "document"

# Document metadata
document:
  title: "Snowflake 账户与平台架构"
  version: "1.0"
  format: "markdown"
