# Snowflake Module Configuration
# Converted from BMAD v4 expansion pack
# Version: 6.0.0-alpha.0
# Date: 2025-10-08

# Module metadata
name: snowflake
version: 1.0.0
short_title: Snowflake System Dev Pack
description: >-
  An expansion pack for BMAD-Method that standardizes Snowflake (Data Cloud)
  system development with agents, workflows, templates, checklists, roles,
  and manifests aligned to BMAD core standards.
author: BMAD Team
tags: [Snowflake, DataCloud, BMAD]
license: MIT

# Custom locations
custom_agent_location: '{project-root}/bmad/snowflake/agents'
custom_workflow_location: '{project-root}/bmad/snowflake/workflows'
custom_module_location: '{project-root}/docs'

# Core Configuration Values
user_name: BMad User
communication_language: English
output_folder: '{project-root}/bmad/snowflake/outputs'

# i18n
defaultLocale: "en"
locales: ["en", "zh-CN"]

# Compatibility
compat:
  bmad-core: ">=1.10"
  runtimes: ["cloud"]
